export const STORAGE_KEY = {
  USER_INFO: "USER_INFO",
  TOKEN: "TOKEN",
  USER_PROFILE: "USER_PROFILE",
  CUSTOMER_LIST: "CUSTOMER_LIST",
  CUSTOMER_INFO: "CUSTOMER_INFO",
  VEHICLE_LIST: "VEHICLE_LIST",
  CUSTOMER_V_LIST: "CUSTOMER_V_LIST",
  VEHICLE_INFO: "VEHICLE_INFO",
};
